### ISSUE TITLE
Alertmanager Service File

### ISSUE THREAD

**Issue by Megzo** [jtyr/prometheus-deb#1]
Hi!

I have encountered an issue: the service file in alertmanager contains two options for the config file  and the storage path. The have one dash in the file instead of two, so when systemd starts the alermanager it goes into an error. If you include the second dash it will work. So it should be:
          --config.file=/etc/prometheus/alertmanager.yml \\
          --storage.path=/var/lib/prometheus/alertmanager \\
instead of:
          -config.file=/etc/prometheus/alertmanager.yml \\
          -storage.path=/var/lib/prometheus/alertmanager \\
 
Best regards,
Peter

**Comment by jtyr** [comment]
Thanks for reporting this issue. I have fixed it and new packages should be available now.
